In [115]:
import pandas as pd
import numpy as np
import requests
import json
import matplotlib.pyplot as plt
import gmaps
import gmaps.datasets
from config import api_google
from config import api_owm
from pprint import pprint

In [116]:
df_path = f"../WeatherPy/output/city_desc2.csv"
df = pd.read_csv(df_path).drop(columns = "Unnamed: 0")

In [117]:
df.head()

    City Name  Temperature (F)  Humidity %  CLoudiness %  Wind Speed (mph)
0   bathsheba            79.23          82            16             20.49
1  melendugno            68.00          64             9              4.70
2       mecca            80.06          16             3              9.40
3     horadiz            69.80          52             0              6.93
4     inirida            74.57          96            95              1.16

In [118]:
humid = df["Humidity %"]

city = df["City Name"]

base_geo = "https://maps.googleapis.com/maps/api/geocode/json?address="
base_place = "https://maps.googleapis.com/maps/api/place/nearbysearch/"

In [119]:
lat_lon=[]

In [120]:
for name in city:
    a=requests.get(base_geo+name + "&key="+api_google).json()
    
    lat_lon.append(a["results"])

In [121]:
pprint(lat_lon[10][0]["address_components"])

[{'long_name': 'Impruneta',
  'short_name': 'Impruneta',
  'types': ['locality', 'political']},
 {'long_name': 'Impruneta',
  'short_name': 'Impruneta',
  'types': ['administrative_area_level_3', 'political']},
 {'long_name': 'Metropolitan City of Florence',
  'short_name': 'FI',
  'types': ['administrative_area_level_2', 'political']},
 {'long_name': 'Tuscany',
  'short_name': 'Tuscany',
  'types': ['administrative_area_level_1', 'political']},
 {'long_name': 'Italy', 'short_name': 'IT', 'types': ['country', 'political']},
 {'long_name': '50023', 'short_name': '50023', 'types': ['postal_code']}]

In [122]:
lat=[]
lon=[]
country=[]
j=0

In [123]:
for i in range(0, len(lat_lon)):
    lat.append (lat_lon[i][0]["geometry"]["location"]["lat"])
    lon.append (lat_lon[i][0]["geometry"]["location"]["lng"])

In [124]:
country

[]

In [125]:
df["lat"]=lat
df["lon"]=lon

In [126]:
#configure gmaps
gmaps.configure(api_key=api_google)

In [127]:
locations = df[['lat','lon']]
weights = df['Humidity %']

fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations, weights = weights) )
fig

Figure(layout=FigureLayout(height='420px'))

In [128]:
#now, let's find ideal vacation spot!
df2 = df[(df["Temperature (F)"]>= 70) & (df["Temperature (F)"]<= 80) & (df["Wind Speed (mph)"]< 10) & (df["CLoudiness %"]< 5) ].reset_index(drop=True)

In [129]:
df2

,City Name,Temperature (F),Humidity %,CLoudiness %,Wind Speed (mph),lat,lon
0,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
1,tabuk,73.11,28,0,8.19,28.383508,36.566191
2,brindisi,72.21,75,0,7.14,40.632728,17.941762
3,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
4,tabuk,73.11,28,0,8.19,28.383508,36.566191
5,brindisi,72.21,75,0,7.14,40.632728,17.941762
6,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
7,tabuk,73.11,28,0,8.19,28.383508,36.566191
8,brindisi,72.21,75,0,7.14,40.632728,17.941762
9,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
10,tabuk,73.11,28,0,8.19,28.383508,36.566191
11,brindisi,72.21,75,0,7.14,40.632728,17.941762
12,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
13,tabuk,73.11,28,0,8.19,28.383508,36.566191
14,brindisi,72.21,75,0,7.14,40.632728,17.941762
15,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
16,tabuk,73.11,28,0,8.19,28.383508,36.566191
17,brindisi,72.21,75,0,7.14,40.632728,17.941762
18,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
19,tabuk,73.11,28,0,8.19,28.383508,36.566191
20,brindisi,72.21,75,0,7.14,40.632728,17.941762
21,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
22,tabuk,73.11,28,0,8.19,28.383508,36.566191
23,brindisi,72.21,75,0,7.14,40.632728,17.941762
24,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
25,tabuk,73.11,28,0,8.19,28.383508,36.566191
26,brindisi,72.21,75,0,7.14,40.632728,17.941762
27,ribeira grande,73.62,74,1,8.25,37.821037,-25.514814
28,inderborskiy,74.23,32,0,9.98,48.548962,51.740292
29,tabuk,73.11,28,0,8.19,28.383508,36.566191
30,brindisi,72.23,74,2,6.69,40.632728,17.941762
31,arraial do cabo,74.71,79,0,9.28,-22.967337,-42.026810

In [134]:
hotel=[]
hotel_name=[]
hotel_lat=[]
hotel_lon=[]
hotel_country=[]
hotel_desc=[]

In [135]:
cor=[]

for i in range(0,len(df2)):
    a=str(df2.iloc[i]["lat"])+","+str(df2.iloc[i]["lon"])
    cor.append(a)

df2["coord"]=cor

In [136]:
# This will return the country name instead of country code, which I think is better!

url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for i in range(0,len(df2)):
    params={"key":api_google,
            "location":df2.loc[i]["coord"],
            "radius":5000,
           "keyword":"hotel"}
    a = requests.get(url, params=params).json()
    hotel_name.append(a["results"][0]["name"])
    b = a["results"][0]["geometry"]["location"]["lat"]
    c = a["results"][0]["geometry"]["location"]["lng"]
    d = a["results"][0]["plus_code"]["compound_code"].split()[-1]
    hotel_lat.append(b)
    hotel_lon.append(c)
    hotel_country.append(d)

In [138]:
#df2["Hotel Location"]=hotel_loc

In [139]:
len(hotel_name)

32

In [140]:
df2["Hotel Name"]=hotel_name

In [141]:
#get hotel data

#    params={"key":api_google,
#            "location":df2.loc[0]["coord"],
#            "radius":5000,
#           "keyword":"hotel"}
#    a = requests.get(url, params=params).json()

In [142]:
#preparing for content
marker_content=[]

for i in range(0, len(df2)):
    a={"Hotel Name":hotel_name[i],
       "City":df2["City Name"][i],
       "Country":hotel_country[i]}
    marker_content.append(a)
    
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**hotel) for hotel in marker_content]

In [143]:
locations = df[['lat','lon']]
weights = df['Humidity %']
marker_locations=df2[['lat','lon']]


fig = gmaps.figure()
markers=gmaps.marker_layer(marker_locations, info_box_content = hotel_info)
fig.add_layer(gmaps.heatmap_layer(locations, weights = weights) )
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))